import type { Metadata } from "next";
// import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Paste your Mailchimp script here */}
        {/* <Script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
              (function(c,h,i,m,p) {
                m=c.createElement(h),p=c.getElementsByTagName(h)[0];
                m.async=1;m.src=i;p.parentNode.insertBefore(m,p);
              })(document,"script","https://chimpstatic.com/mcjs-connected/js/users/683f45251417b61f67e601f68/1ac3b0c4f04e80bd7eee5e765.js");
            `,
          }}
        /> */}
        {children}
      </body>
    </html>
  );
}
